# Homework 2 (5 points).

All tasks below have equal weight (5/16).

In [2]:
import pandas as pd

#### Description of data

The Data folder contains information about students. There are 10 groups of students in total. Files are divided into two categories:
    * Students_info_i - information about students from group i
    * Students_marks_i - grades of students from group i for exams

### One of the important advantages of pandas $-$ is convenient methods of relational interaction with data, similar, for example, to SQL capabilities for merging and concatenating tables: merge, join, concat. The presence of ready-made methods allows you not to implement element-by-element data processing yourself and operate with entire data tables at once.

Find out more about these methods here: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Task 1. Collect all information about students into one df table. The resulting table should contain information and grades of all students from all groups. Print a few rows of the table to show the result.¶

In [35]:
df_st = pd.read_csv('Students_info_0.csv', sep=',', index_col=0)
df_m = pd.read_csv('Students_marks_0.csv', sep=',', index_col=0)
for i in range(1, 10):
    name_st = 'Students_info_' + str(i) + '.csv'
    name_m = 'Students_marks_' + str(i) + '.csv'
    df_st_new = pd.read_csv(name_st, sep=',', index_col=0)
    df_st = pd.concat([df_st, df_st_new])
    df_m_new = pd.read_csv(name_m, sep=',', index_col=0)
    df_m = pd.concat([df_m, df_m_new])
df = pd.concat([df_st, df_m], axis=1)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
index,,,,,,,,,
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75

#### Task 2. Remove the index column from the resulting table. Print the first 10 rows of the table.

In [36]:
df = df.reset_index(drop=True)
print(df.head(10))

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard
5  female        group B          associate's degree      standard
6  female        group B                some college      standard
7    male        group B                some college  free/reduced
8    male        group D                 high school  free/reduced
9  female        group B                 high school  free/reduced

  test preparation course   group  math score  reading score  writing score
0                    none  group1          72             72             74
1               completed  group1          69             90             88
2                    none  group1          90             95             93
3                    none  group1          47             57             44
4                    none  group1          76             78             75
5                    none  group1          71             83             78
6               completed  group1          88             95             92
7                    none  group1          40             43             39
8               completed  group1          64             64             67
9                    none  group1          38             60             50

#### Task 3. Display the dimensions of the resulting table

In [37]:
print(df.shape)

(1000, 9)

#### Task 4. Display the statistical characteristics of the numerical columns of the table (minimum, maximum, average, standard deviation)

In [38]:
df.describe().loc[['min', 'max', 'mean', 'std']]

      math score  reading score  writing score
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657

#### Task 5. Check if there are missing values ​​in the table

In [39]:
if df.isnull().sum().sum() > 0:
    print('The table has missing values')
else:
    print('There are no missing values ​​in the table')

В таблице нет пропущенных значений

#### Task 6. Display the average scores of students in each subject (math, reading, writing)

In [40]:
df[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Task 7. How do grades depend on whether the student took a test preparation course? Display the average score of students who took the test prep course and those who did not take the course for each subject separately.**

In [41]:
math_mean = df.groupby('test preparation course')["math score"].mean()
read_mean = df.groupby('test preparation course')["reading score"].mean()
writ_mean = df.groupby('test preparation course')["writing score"].mean()
print(math_mean, read_mean, writ_mean)

test preparation course
completed    69.695531
none         64.077882
Name: math score, dtype: float64 test preparation course
completed    73.893855
none         66.534268
Name: reading score, dtype: float64 test preparation course
completed    74.418994
none         64.504673
Name: writing score, dtype: float64

**Task 8. Display all the different values ​​from the lunch column.**

In [42]:
df.lunch.unique()

array(['standard', 'free/reduced'], dtype=object)

**Task 9. Rename the column "parental level of education" to "education" and "test preparation course" to "test preparation" using the pandas rename method**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [43]:
df = df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})

**We will fix the minimum score to pass the exam**

In [44]:
passmark = 50

**Task 10. Answer the questions:**
    * What proportion of students passed the mathematics exam (passmark >= 50)?
    * What proportion of students who took the test preparation course passed the math exam?
    * What proportion of women who did not take the test preparation course fail the math test?

In [45]:
passed_math = (df.loc[(df["math score"] >= passmark)]['math score'].count())/(df['math score'].count())
prepared_math = (df.loc[(df["math score"] >= passmark) & (df['test preparation'] == 'completed')]['math score'].count())/(df.loc[(df['test preparation'] == 'completed')]['math score'].count())
not_prep_w = (df.loc[(df["math score"] < passmark) & (df['test preparation'] == 'none') & (df['gender'] == 'female')]['math score'].count())/(df.loc[(df['test preparation'] == 'none') & (df['gender'] == 'female')]['math score'].count())
print(passed_math, prepared_math, not_prep_w)

0.865 0.9217877094972067 0.20958083832335328

**Task 11. Use groupby to complete the tasks below. Also print the execution time for each task.**
    *For each ethnic group, print the average reading test score.
    * For each education level, print the minimum writing exam score.

In [46]:
%%time
read_mean = df.groupby('race/ethnicity')['reading score'].mean()
writ_min = df.groupby('education')['writing score'].min()
print(read_mean, '\n', writ_min)

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64
 education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64
CPU times: user 15.6 ms, sys: 0 ns, total: 15.6 ms
Wall time: 12 ms

**Task 12. Complete task 11 using loops. Compare execution time.**

In [47]:
%%time
shtuka = df['race/ethnicity'].unique()
sl_1 = {key: 0 for key in shtuka}
sl_2 = {key: 0 for key in shtuka}
level = df['education'].unique()
sl_min = {key: [100] for key in level}
for index, row in df.iterrows():
    sl_1[row['race/ethnicity']] += row['reading score']
    sl_2[row['race/ethnicity']] += 1
for key in sl_1:
    sl_1[key] = sl_1[key]/sl_2[key]
    print(key, sl_1[key])
print('\n')
for index, row in df.iterrows():
    sl_min[row['education']].append(row['writing score'])
for key in sl_min:
    print(key, min(sl_min[key]))

group B 67.35263157894737
group C 69.10344827586206
group A 64.67415730337079
group D 70.03053435114504
group E 73.02857142857142


bachelor's degree 38
some college 19
master's degree 46
associate's degree 35
high school 15
some high school 10
CPU times: user 203 ms, sys: 0 ns, total: 203 ms
Wall time: 209 ms

**Task 13. Display the average scores of students in each subject depending on gender and level of education. That is, the number of groups should be equal to 2 * (the number of levels of education), and for each such group, print the average score for each of the subjects.**

This can be done using pivot tables (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [48]:
pd.pivot_table(df,index=['gender','education'])

/tmp/ipykernel_69/940922539.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  pd.pivot_table(df,index=['gender','education'])

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

#### Task 14. How many students successfully passed the mathematics exam?

Create a new column in the df table called Math_PassStatus and record F if the student failed the math exam (exam score < passmark), and P otherwise.

Count the number of students who passed and failed the math exam.

Follow similar steps for reading and writing exams.

In [49]:
def func(score):
    if score >= passmark:
        return 'P'
    else:
        return 'F'
df['Math_PassStatus'] = df["math score"].apply(func)
print('Math. Passed: ', df.loc[(df['Math_PassStatus'] == 'P')]['Math_PassStatus'].count(), 'Failed: ', df.loc[(df['Math_PassStatus'] == 'F')]['Math_PassStatus'].count())
df['Reading_PassStatus'] = df["reading score"].apply(func)
print('Reading. Passed: ', df.loc[(df['Reading_PassStatus'] == 'P')]['Reading_PassStatus'].count(), 'Failed: ', df.loc[(df['Reading_PassStatus'] == 'F')]['Reading_PassStatus'].count())
df['Writing_PassStatus'] = df["writing score"].apply(func)
print('Writing. Passed: ', df.loc[(df['Writing_PassStatus'] == 'P')]['Writing_PassStatus'].count(), 'Failed: ', df.loc[(df['Writing_PassStatus'] == 'F')]['Writing_PassStatus'].count())
df.head()

Math. Passed:  865 Failed:  135
Reading. Passed:  910 Failed:  90
Writing. Passed:  886 Failed:  114

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P

#### Task 15. How many students successfully passed all exams?

Create a column called OverAll_PassStatus and record an 'F' for each student if the student fails at least one of the three exams, and a 'P' otherwise.

Count the number of students who passed all exams.

In [50]:
def ov_p(m1, m2, m3):
    if (m1 == 'P') and (m2 == 'P') and (m3 == 'P'):
        return 'P'
    else:
        return 'F'
df['OverAll_PassStatus'] = df.apply(lambda x: ov_p(x.Math_PassStatus, x.Reading_PassStatus, x.Writing_PassStatus), axis=1)
print('number of students who passed all exams:', df.loc[(df['OverAll_PassStatus'] == 'P')]['OverAll_PassStatus'].count())
df.head()

количество студентов, которые сдали все экзамены:  812

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P

#### Task 16. Convert points into grades

### System for converting points into grades
#### greater than 90 = A
#### 80-90 = B
#### 70-80 = C
#### 60-70 = D
#### 50-60 = E
#### less than 50 = F (Fail)

Create an auxiliary function that, based on the average score for three exams, will grade the student according to the criteria given above.

Create a Grade column and record each student's grade in it.

Print the number of students who received each grade.

**If the average score falls on the border between grades (i.e. equal to exactly 60, 70 or 80 points), you can interpret the condition at your discretion (i.e. you can give a grade of D for 60 points, or you can give an E).**

In [51]:
def GetGrade(average_mark):
    if average_mark >= 90:
        return 'A'
    elif average_mark >= 80:
        return 'B'
    elif average_mark >= 70:
        return 'C'
    elif average_mark >= 60:
        return 'D'
    elif average_mark >= 50:
        return 'E' 
    else:
        return 'F'

df['Grade_avg'] = df[['math score', 'reading score', 'writing score']].mean(axis=1)
df['Grade'] = df['Grade_avg'].apply(GetGrade)
df.pop('Grade_avg')
print(df.groupby(['Grade'])['Grade'].count())
df.head()

Grade
A     52
B    146
C    261
D    256
E    182
F    103
Name: Grade, dtype: int64

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Grade
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P,C
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P,B
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P,A
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P,C